name: Unit testing
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Unit testing ..."
      - name: Print goodbye
        run: echo "Done."
      
